const constants = {
  API: "API",
  API_START: "API_START",
  API_END: "API_END",
  API_ERROR: "API_ERROR",
  SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
  DELETE_MOVIE: "DELETE_MOVIE",
  OPEN_EDIT_MODAL: "OPEN_EDIT_MODAL",
  CLOSE_EDIT_MODAL: "CLOSE_EDIT_MODAL",
  OPEN_DELETE_MODAL: "OPEN_DELETE_MODAL",
  CLOSE_DELETE_MODAL: "CLOSE_DELETE_MODAL",
  ADD_MOVIE_TO_EDIT: "ADD_MOVIE_TO_EDIT",
  ADD_MOVIE_TO_DELETE: "ADD_MOVIE_TO_DELETE",
};

export default constants;
